services:
  codeup-postgres-db:
    image: bitnami/postgresql:latest
    container_name: codeup-postgres-db
    ports:
      - "5433:5432"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USER:-docker}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-docker}
      - POSTGRES_DB=codeup
    volumes:
      - db_volume:/bitnami/postgresql
    networks:
      - local-network

  codeup-pg-admin:
    image: dpage/pgadmin4:latest
    container_name: codeup-pg-admin
    depends_on:
      - codeup-postgres-db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-user@localhost.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - 8081:80
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - local-network

  codeup-php:
    container_name: codeup-php
    build:
      context: ./php
    ports:
      - "8000:80"
    volumes:
      - ./php:/var/www/html
    networks:
      - local-network
    depends_on:
      - codeup-postgres-db
    restart: unless-stopped
    env_file:
      - ./php/.env

  codeup-next:
    container_name: codeup-next
    dns:
      - 8.8.8.8
      - 8.8.4.4
    build:
      context: ./next
      target: production
      args:
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
        NEXTAUTH_URL: ${NEXTAUTH_URL}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
        API_URL: ${API_URL}
        NEXT_PUBLIC_VALIDATOR_API_URL: ${NEXT_PUBLIC_VALIDATOR_API_URL}
    restart: unless-stopped
    env_file:
      - ./next/.env
    ports:
      - "3000:3000"
    depends_on:
      - codeup-php
      - codeup-nodejs
    networks:
      - local-network
    command: sh -c "pnpm migrate deploy && pnpm start"

  codeup-nodejs:
    container_name: codeup-nodejs
    dns:
      - 8.8.8.8
      - 8.8.4.4
    build:
      context: ./nodejs
      target: runner
    env_file:
      - ./nodejs/.env
    depends_on:
      - codeup-postgres-db
    ports:
      - "3030:3030"
    restart: unless-stopped
    networks:
      - local-network
    command: sh -c "pnpm migrate dev && pnpm start"

volumes:
  db_volume:
  pgadmin_data:
  php_data:

networks:
  local-network:
    driver: bridge