FROM node:22-alpine AS base

# Instala o pnpm globalmente
RUN npm install -g pnpm

WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json pnpm-lock.yaml* ./
RUN pnpm install --frozen-lockfile

FROM base AS dev

WORKDIR /app
# COPY --from=deps /app/node_modules ./node_modules
COPY ./app .

# Gera o Prisma Client (agora com as dependências e o schema disponíveis)
RUN pnpm generate

EXPOSE 3000