# Etapa 1: Builder
FROM node:20-alpine AS builder
RUN npm install -g pnpm
WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .

RUN pnpm build
RUN pnpm prune --production

# Etapa 2: Runner (Execução)
FROM node:20-alpine AS runner
RUN npm install -g pnpm
WORKDIR /app

# 1. Cria o usuário
RUN addgroup -S appgroup && adduser -S appuser -G appgroup

# 2. Copia arquivos necessários
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/pnpm-lock.yaml ./pnpm-lock.yaml
COPY --from=builder /app/prisma ./prisma
# COPY --from=builder /app/node_modules/swagger-ui-dist /app/node_modules/swagger-ui-dist
COPY --from=builder /app/dist ./dist

# 3. Instala dependências de produção
RUN pnpm install --prod --frozen-lockfile

# 🔧 4. Gera Prisma Client aqui mesmo
RUN pnpm generate

# 5. Permissões e troca de usuário
RUN chown -R appuser:appgroup /app
USER appuser

EXPOSE ${API_PORT}
CMD ["pnpm", "start"]